let finishLine = {
  "version" : "0.1.0",

  "comment" : "Generated by MeshLab JSON Exporter",

  "id"      : 1,
  "name"    : "mesh",

  "vertices" :
  [
    {
      "name"       : "position_buffer",
      "size"       : 3,
      "type"       : "float32",
      "normalized" : false,
      "values"     :
      [
        1e-06, 15, 30, -1e-06, -15, 30, 1e-06, 15, -30, -1e-06, -15, -30
      ]
    },

    {
      "name"       : "normal_buffer",
      "size"       : 3,
      "type"       : "float32",
      "normalized" : false,
      "values"     :
      [
        1, -0, 0, 1, -0, 0, 1, -0, 0, 1, -0, 0
      ]
    },

    {
      "name"       : "color_buffer",
      "size"       : 4,
      "type"       : "uint8",
      "normalized" : true,
      "values"     :
      [
        192, 192, 192, 255, 192, 192, 192, 255, 192, 192, 192, 255, 192, 192, 192, 255
      ]
    },

    {
      "name"       : "texcoord_buffer",
      "size"       : 2,
      "type"       : "float32",
      "normalized" : false,
      "values"     :
      [
        0, 0, 1, 0, 0, 1, 1, 1
      ]
    }
  ],

  "connectivity" :
  [
    {
      "name"      : "triangles",
      "mode"      : "triangles_list",
      "indexed"   : true,
      "indexType" : "uint32",
      "indices"   :
      [
        0, 1, 3, 0, 3, 2
      ]
    }
  ],

  "mapping" :
  [
    {
      "name"       : "standard",
      "primitives" : "triangles",
      "attributes" :
      [
        {
          "source"   : "position_buffer",
          "semantic" : "position",
          "set"      : 0
        },
        {
          "source"   : "normal_buffer",
          "semantic" : "normal",
          "set"      : 0
        },
        {
          "source"   : "color_buffer",
          "semantic" : "color",
          "set"      : 0
        },
        {
          "source"   : "texcoord_buffer",
          "semantic" : "texcoord",
          "set"      : 0
        }
      ]
    }
  ],

  "custom" : null
}
