---
deployment:
  tasks:
    - export DEPLOYPATH=/public_html
    - /bin/cp -R /repositories/zachlavake/public_html/html $DEPLOYPATH
    - /bin/cp -R /repositories/zachlavake/public_html/stylesheets $DEPLOYPATH
    - /bin/cp -R /repositories/zachlavake/public_html/javascripts $DEPLOYPATH