---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zachlava/public_html/
    - repositories/zachlavake/public_html/html -R html $DEPLOYPATH
    - repositories/zachlavake/public_html/stylesheets -R stylesheets $DEPLOYPATH
    - repositories/zachlavake/public_html/javascripts -R javascripts $DEPLOYPATH