---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zachlava/public_html/
    - /bin/cp -R /home/zachlava/repositories/zachlavake/public_html/index.html $DEPLOYPATH
    - /bin/cp -R /home/zachlava/repositories/zachlavake/public_html/html $DEPLOYPATH
    - /bin/cp -R /home/zachlava/repositories/zachlavake/public_html/stylesheets $DEPLOYPATH
    - /bin/cp -R /home/zachlava/repositories/zachlavake/public_html/javascripts $DEPLOYPATH